import '@mdi/font/css/materialdesignicons.css';
import '../assets/scss/styles.scss';

import DayJsAdapter from '@date-io/dayjs';
import { createVuetify } from 'vuetify';
import { md3 } from 'vuetify/blueprints';

export default defineNuxtPlugin((app) => {
  const vuetify = createVuetify({
    blueprint: md3,
    ssr: false,
    theme: {
      defaultTheme: process.client
        ? localStorage.getItem('theme:mode') ?? 'coffee'
        : 'coffee',
      themes: {
        light: {
          colors: {
            primary: '#3C5BA9',
            'on-primary': '#FFFFFF',
            'primary-container': '#DBE1FF',
            'on-primary-container': '#001849',
            secondary: '#585E71',
            'on-secondary': '#FFFFFF',
            'secondary-container': '#DDE2F9',
            'on-secondary-container': '#151B2C',
            tertiary: '#7D4895',
            'on-tertiary': '#FFFFFF',
            'tertiary-container': '#F7D8FF',
            'on-tertiary-container': '#310048',
            background: '#FEFBFF',
            'on-background': '#1B1B1F',
            surface: '#FEFBFF',
            'on-surface': '#1B1B1F',
            'surface-variant': '#E2E2EC',
            'on-surface-variant': '#45464F',
            outline: '#757680',
            'on-inverse-surface': '#F2F0F4',
            'inverse-surface': '#303034',
            'inverse-primary': '#B3C5FF',
            shadow: '#000000',
            'surface-tint': '#3C5BA9',
            'outline-variant': '#C5C6D0',
            scrim: '#000000',
            error: '#BA1A1A',
            'on-error': '#FFFFFF',
            'error-container': '#FFDAD6',
            'on-error-container': '#410002',
            success: '#006B5F',
            'on-success': '#FFFFFF',
            'success-container': '#75F8E4',
            'on-success-container': '#00201C',
            'surface-container-lowest': '#F4F3FB',
            'surface-container-low': '#EEEEF8',
            'surface-container': '#E9E9F6',
            'surface-container-high': '#E7E8F5',
            'surface-container-highest': '#E3E5F3',
          },
        },
        dark: {
          colors: {
            primary: '#B3C5FF',
            'on-primary': '#002B75',
            'primary-container': '#21428F',
            'on-primary-container': '#DBE1FF',
            secondary: '#C1C6DD',
            'on-secondary': '#2A3042',
            'secondary-container': '#414659',
            'on-secondary-container': '#DDE2F9',
            tertiary: '#E9B3FF',
            'on-tertiary': '#4B1763',
            'tertiary-container': '#63307C',
            'on-tertiary-container': '#F7D8FF',
            background: '#1B1B1F',
            'on-background': '#E4E2E6',
            surface: '#1B1B1F',
            'on-surface': '#E4E2E6',
            'surface-variant': '#45464F',
            'on-surface-variant': '#C5C6D0',
            outline: '#8F909A',
            'on-inverse-surface': '#1B1B1F',
            'inverse-surface': '#E4E2E6',
            'inverse-primary': '#3C5BA9',
            shadow: '#000000',
            'surface-tint': '#B3C5FF',
            'outline-variant': '#45464F',
            scrim: '#000000',
            error: '#FFB4AB',
            'on-error': '#690005',
            'error-container': '#93000A',
            'on-error-container': '#FFDAD6',
            success: '#54DBC8',
            'on-success': '#003731',
            'success-container': '#005047',
            'on-success-container': '#75F8E4',
            'surface-container-lowest': '#23242A',
            'surface-container-low': '#272931',
            'surface-container': '#2C2E38',
            'surface-container-high': '#2D2F3A',
            'surface-container-highest': '#30333E',
          },
        },
        coffee: {
          colors: {
            primary: '#9C413E',
            'on-primary': '#FFFFFF',
            'primary-container': '#FFDAD7',
            'on-primary-container': '#410005',
            secondary: '#775654',
            'on-secondary': '#FFFFFF',
            'secondary-container': '#FFDAD7',
            'on-secondary-container': '#2C1514',
            tertiary: '#735B2E',
            'on-tertiary': '#FFFFFF',
            'tertiary-container': '#FFDEA7',
            'on-tertiary-container': '#271900',
            background: '#FFFBFF',
            'on-background': '#201A1A',
            surface: '#FFFBFF',
            'on-surface': '#201A1A',
            'surface-variant': '#F5DDDB',
            'on-surface-variant': '#534342',
            outline: '#857371',
            'on-inverse-surface': '#FBEEEC',
            'inverse-surface': '#362F2E',
            'inverse-primary': '#FFB3AE',
            shadow: '#000000',
            'surface-tint': '#9C413E',
            'outline-variant': '#D8C2C0',
            scrim: '#000000',
            error: '#BC004C',
            'on-error': '#FFFFFF',
            'error-container': '#FFD9DE',
            'on-error-container': '#400015',
            success: '#346A22',
            'on-success': '#FFFFFF',
            'success-container': '#B4F39A',
            'on-success-container': '#042100',
            'surface-container-lowest': '#FAF2F5',
            'surface-container-low': '#F7ECF0',
            'surface-container': '#F4E7EA',
            'surface-container-high': '#F3E5E8',
            'surface-container-highest': '#F1E1E4',
          },
        },
      },
    },
    defaults: {
      VTextField: {
        variant: 'outlined',
        rounded: 'lg',
        hideDetails: true,
      },
    },
    date: {
      adapter: DayJsAdapter,
    },
  });
  app.vueApp.use(vuetify);
});
